spring: 
  application: 
    name: api-gateway

server:
  port: 8096
  context-path: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://:xxxxx/eureka/

zuul: 
  routes: 
    api-a: 
      path: /api-a/**
      serviceId: cqm-sctest-provider
    api-b: 
      path: /api-b/**
      serviceId: sctest-consumer